### PR TITLE
Integrate outstanding branches

### PR DESCRIPTION
**Pull request by mbenson1**
Ensure the following build:

[ ] - bebop2/default -  Verify it builds.  Verify make docs builds.
[ ] - bebop2/sitl -  Verify it builds.  Verify it executes.  Verify ctest builds and passes.  Verify make docs builds.
[ ] - ocpoc/default -  Verify it builds.  Verify it executes on target.  Verify make docs builds.
[ ] - ocpoc/quadx -  Verify it builds.  Verify it executes on target.  Verify make docs builds.
[ ] - tutorial/cfs -  Verify it builds.  Verify it executes.  Verify ctest builds and passes.  Verify make docs builds.
[ ] - tutorial/airliner -  Verify it builds.  Verify it executes.  Verify ctest builds and passes.  Verify make docs builds.

Also:
[ ] - docs-doxygen  -  Verify it builds.
[ ] - docs-sphinx - Verify it builds.

### CODE REVIEW

**Review by lorenzo-gomez-windhover — COMMENTED** [review]
- [ ]  docs-doxygen - Verify it builds.
- [x]  docs-sphinx - Verify it builds.


Tested `docs-doxygen`, `docs-sphinx` and `docs` on a `Ubuntu 18` isolated docker container, and it builds just fine :+1:.

One thing to mention which you might be aware of already is that the following diagrams do not render correctly on the browser:
```
/Applications/Actuator Motor Control/Design
/Applications/File Delivery/Design
/Applications/CFS/Library/Design
/Applications/Current Value Table/Design
/Applications/Data Storage/Design
/Applications/External Application/Design
/Applications/File Manager/Design
/Applications/Housekeeping/Design
/Applications/Health Services/Design
/Applications/File Manager/Design
/Applications/Limit Checker/Design
/Applications/Landing Detector/Design
/Applications/Multicopter Attitude Control/Design
/Applications/Mavlink/Design
/Applications/Memory Dwell/Design
/Applications/Memory Manager/Design
/Applications/Protocol Buffer Library/Design
/Applications/Stored Command/Design
/Applications/Scheduler/Design
/Applications/Telemetry Output/Design

```

**Review by grahamwh — COMMENTED** [review]
Built and executed on target only:
make ocpoc/default
make ocpoc/quadx

Built and executed on PC only:
make tutorial/cfs

Failed to build:
make bebop2/default  #error: missing ea_mission_cfg.h
make bebop2/sitl  #error: missing Findgazebo.cmake
make tutorial/airliner  #error: missing bits/c++config.h

**Comment by lorenzo-gomez-windhover** [comment]
@grahamwh This error `make tutorial/airliner #error: missing bits/c++config.h` can be fixed with the following:
```
sudo apt-get install g++-multilib
sudo apt-get install gcc-multilib
```
These are dependencies we should document in the future to make it a little easier for users.

**Comment by grahamwh** [comment]
Tests passed on hash `e1809c48935d3389c8d8fbd5147d8d87ad38d637`:

Name | Make Build | Run on Target | Run on Desktop | Unit Test
-- | -- | -- | -- | --
bebop2/default | Pass |  |  | 
bebop2/sitl | Pass |  | Pass | Pass
ocpoc/default | Pass | Pass |  | 
ocpoc/quadx | Pass | Pass |  | 
tutorial/cfs | Pass |  | Pass | Pass
tutorial/airliner | Pass |  | Pass | Pass
docs-doxygen | Pass |  |  | 
docs-sphinx | Pass |  |  |

**Pull request merged**
